<a href="https://colab.research.google.com/github/StarGonich/The-basics-of-Neural-networks/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import math
import numpy as np
import time
## Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()
## Progress bar
from tqdm.notebook import tqdm

<ipython-input-1-efb065ca8ec2>:9: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats('svg', 'pdf') # For export


In [ ]:
import torch
print("Using torch", torch.__version__)

Using torch 2.4.0+cu121


In [ ]:
torch.manual_seed(42) # Setting the seed

In [ ]:
x = torch.Tensor(2, 3, 4)
print(x)

tensor([[[-1.5542e-13,  4.5394e-41, -1.5542e-13,  4.5394e-41],
         [ 4.4842e-44,  0.0000e+00,  8.9683e-44,  0.0000e+00],
         [ 1.3558e-10,  3.3457e-41,  0.0000e+00,  1.1755e-38]],

        [[-5.9317e+32,  3.3453e-41,  1.0842e-19,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  4.6243e-44,  0.0000e+00]]])


In [ ]:
x = torch.Tensor([[1, 2], [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
